import ast
import sys

from PyQt5 import QtGui, QtWidgets, QtCore
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QDialog, QLabel, QDialogButtonBox, QVBoxLayout

from src.customer import Customer
from src.db import DB


class GUIMain:
    cust = None

    def __init__(self):
        try:
            self.app = QApplication(sys.argv)
            self.mainWindow = QMainWindow()
            # load db & Create table
            self.mydb = DB()
        except Exception as e:
            show_dialog("Error while loading GUI : " + e)

    def setup_gui(self):
        self.mainWindow.setObjectName("MainWindow")
        self.mainWindow.resize(1387, 695)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mainWindow.setFont(font)
        self.mainWindow.setAutoFillBackground(False)
        self.mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(self.mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1460, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 0);\n"
                                 "background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 431, 641))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 151, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.line1 = QtWidgets.QLineEdit(self.groupBox)
        self.line1.setGeometry(QtCore.QRect(151, 39, 270, 22))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(self.groupBox)
        self.line2.setGeometry(QtCore.QRect(151, 85, 271, 22))
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QLineEdit(self.groupBox)
        self.line3.setGeometry(QtCore.QRect(151, 131, 270, 22))
        self.line3.setObjectName("line3")
        self.line5 = QtWidgets.QLineEdit(self.groupBox)
        self.line5.setGeometry(QtCore.QRect(151, 223, 270, 22))
        self.line5.setObjectName("line5")
        self.line6 = QtWidgets.QLineEdit(self.groupBox)
        self.line6.setGeometry(QtCore.QRect(151, 269, 270, 22))
        self.line6.setObjectName("line6")
        self.line7 = QtWidgets.QLineEdit(self.groupBox)
        self.line7.setGeometry(QtCore.QRect(151, 315, 270, 22))
        self.line7.setObjectName("line7")
        self.line10 = QtWidgets.QLineEdit(self.groupBox)
        self.line10.setGeometry(QtCore.QRect(151, 453, 270, 22))
        self.line10.setObjectName("line10")
        self.line11 = QtWidgets.QLineEdit(self.groupBox)
        self.line11.setGeometry(QtCore.QRect(151, 499, 270, 22))
        self.line11.setObjectName("line11")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 530, 411, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_2.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_2.addWidget(self.btn3)
        self.btn4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_2.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn5.setObjectName("btn5")
        self.horizontalLayout_2.addWidget(self.btn5)
        self.comboBox1 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox1.setGeometry(QtCore.QRect(150, 170, 271, 22))
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 360, 271, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 410, 271, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 50, 931, 641))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.lineinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineinput.setGeometry(QtCore.QRect(362, 30, 331, 20))
        self.lineinput.setObjectName("lineinput")
        self.btn6 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn6.setGeometry(QtCore.QRect(704, 30, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn7.setGeometry(QtCore.QRect(814, 30, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("color: rgb(255, 255, 0);\n"
                                "background-color: rgb(0, 0, 0);")
        self.btn7.setObjectName("btn7")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 891, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 30, 241, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")

        self.mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.mainWindow)
        self.statusbar.setObjectName("statusbar")
        self.mainWindow.setStatusBar(self.statusbar)

        self.btn2.clicked.connect(self.insert_data)
        self.btn3.clicked.connect(self.update_data)
        self.btn4.clicked.connect(self.delete_data)
        self.btn5.clicked.connect(self.reset_data)
        self.btn6.clicked.connect(self.search_data)
        self.btn7.clicked.connect(self.show_all)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.mainWindow)

        event_filter = EventHandler()
        event_filter.tableWidget = self.tableWidget
        event_filter.parent = self
        self.tableWidget.viewport().installEventFilter(event_filter)

        self.mainWindow.show()
        sys.exit(self.app.exec_())

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.mainWindow.setWindowTitle(_translate("MainWindow", "CUSTOMER"))
        self.label.setText(_translate("MainWindow",
                                      "                                                                                         ADD CUSTOMER DETEILS"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer Details"))
        self.label_6.setText(_translate("MainWindow", "Customer ref"))
        self.label_5.setText(_translate("MainWindow", "Customer Name"))
        self.label_4.setText(_translate("MainWindow", "No.of People"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.label_7.setText(_translate("MainWindow", "Post Code"))
        self.label_8.setText(_translate("MainWindow", "Mobile"))
        self.label_9.setText(_translate("MainWindow", "Email"))
        self.label_10.setText(_translate("MainWindow", "Nationality"))
        self.label_11.setText(_translate("MainWindow", "Id Proof Type"))
        self.label_12.setText(_translate("MainWindow", "Id Number"))
        self.label_13.setText(_translate("MainWindow", "Address"))
        self.btn2.setText(_translate("MainWindow", "Add"))
        self.btn3.setText(_translate("MainWindow", "Update"))
        self.btn4.setText(_translate("MainWindow", "Delete"))
        self.btn5.setText(_translate("MainWindow", "Reset"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "male"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "female"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "others"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "indian"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "usa"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "brazil"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "pakistan"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "addhar"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "pan_card"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "driving_card"))
        self.groupBox_2.setTitle(_translate("MainWindow", "View Details and Search System"))
        self.label_3.setText(_translate("MainWindow", "Search By"))
        self.btn6.setText(_translate("MainWindow", "Search"))
        self.btn7.setText(_translate("MainWindow", "Show All"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "customer ref"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "no.of people"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "gender"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "post code"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "mobile"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "email"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "nationality"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "id proof"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "id number"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "address"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "MOBILE"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "EMAIL"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "CUST_NAME"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "ID_NUMBER"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "CUST_REF"))

    def insert_data(self):
        cust = Customer()
        cust.cust_ref = self.line1.text()
        cust.cust_name = self.line2.text()
        cust.people_cnt = self.line3.text()
        cust.gender = self.comboBox1.currentText()
        cust.pincode = self.line5.text()
        cust.mobile = self.line6.text()
        cust.email = self.line7.text()
        cust.nationality = self.comboBox_2.currentText()
        cust.id_proof_type = self.comboBox_3.currentText()
        cust.id_number = self.line10.text()
        cust.cust_address = self.line11.text()
        cust.db_obj = self.mydb
        try:
            cust.verify()
            self.mydb.insert_data(cust)
            self.reset_data()
            show_dialog('Record inserted successfully...')
        except Exception as e:
            show_dialog("Error occurred while inserting record to table : " + e)

    def update_data(self):
        cust = Customer()
        cust.cust_ref = self.line1.text()
        cust.cust_name = self.line2.text()
        cust.people_cnt = self.line3.text()
        cust.gender = self.comboBox1.currentText()
        cust.pincode = self.line5.text()
        cust.mobile = self.line6.text()
        cust.email = self.line7.text()
        cust.nationality = self.comboBox_2.currentText()
        cust.id_proof_type = self.comboBox_3.currentText()
        cust.id_number = self.line10.text()
        cust.cust_address = self.line11.text()
        cust.db_obj = self.mydb
        try:
            if self.cust == None:
                raise Exception("Select row to update")
            cust.compare_and_verify(self.cust)
            self.mydb.update_data(self.cust, cust)
            self.show_all()
            show_dialog('Record updated successfully...')
        except Exception as e:
            show_dialog("Update Error : " + e)

    def delete_data(self):
        try:
            if self.cust == None:
                raise Exception("Select row to delete")
            self.cust.db_obj = self.mydb
            self.mydb.delete_data(self.cust)
            self.show_all()
            show_dialog('Record deleted successfully...')
        except Exception as e:
            show_dialog("Deletion Error : " + e)

    def reset_data(self):
        try:
            self.line1.setText('')
            self.line2.setText('')
            self.line3.setText('')
            self.comboBox1.setCurrentIndex(0)
            self.line5.setText('')
            self.line6.setText('')
            self.line7.setText('')
            self.comboBox_2.setCurrentIndex(0)
            self.comboBox_3.setCurrentIndex(0)
            self.line10.setText('')
            self.line11.setText('')
            self.lineinput.setText('')
        except Exception as e:
            show_dialog('Unable to reset, Error : ' + e)

    def show_all(self):
        try:
            data = self.mydb.search({})
            self.tableWidget.setRowCount(0)
            for row in data:
                self.add_table(my_converter(row))
            self.reset_data()
        except Exception as e:
            show_dialog("Error while reading rows from table : " + e)

    def search_data(self):
        try:
            key = self.comboBox_4.currentText()
            value = self.lineinput.text().strip()
            data = self.mydb.search({key: value})
            self.tableWidget.setRowCount(0)
            for row in data:
                self.add_table(my_converter(row))
            self.reset_data()
        except Exception as e:
            show_dialog("Error while finding matching rows : " + e)

    def add_table(self, columns):
        row_position = self.tableWidget.rowCount()
        self.tableWidget.insertRow(row_position)

        for i, column in enumerate(columns):
            self.tableWidget.setItem(row_position, i, QtWidgets.QTableWidgetItem(str(column)))

    def load_row(self, row_index):
        self.cust = Customer()
        try:
            cols = self.tableWidget.columnCount()
            self.cust.cust_ref = self.tableWidget.item(row_index, 0).text()
            self.line1.setText(self.cust.cust_ref)
            self.cust.cust_name = self.tableWidget.item(row_index, 1).text()
            self.line2.setText(self.cust.cust_name)
            self.cust.people_cnt = self.tableWidget.item(row_index, 2).text()
            self.line3.setText(self.cust.people_cnt)
            self.cust.gender = self.tableWidget.item(row_index, 3).text()
            self.comboBox1.setCurrentText(self.cust.gender)
            self.cust.pincode = self.tableWidget.item(row_index, 4).text()
            self.line5.setText(self.cust.pincode)
            self.cust.mobile = self.tableWidget.item(row_index, 5).text()
            self.line6.setText(self.cust.mobile)
            self.cust.email = self.tableWidget.item(row_index, 6).text()
            self.line7.setText(self.cust.email)
            self.cust.nationality = self.tableWidget.item(row_index, 7).text()
            self.comboBox_2.setCurrentText(self.cust.nationality)
            self.cust.id_proof_type = self.tableWidget.item(row_index, 8).text()
            self.comboBox_3.setCurrentText(self.cust.id_proof_type)
            self.cust.id_number = self.tableWidget.item(row_index, 9).text()
            self.line10.setText(self.cust.id_number)
            self.cust.cust_address = self.tableWidget.item(row_index, 10).text()
            self.line11.setText(self.cust.cust_address)
        except Exception as e:
            show_dialog('Unable to load row, Error : ' + e)


class EventHandler(QWidget):
    tableWidget = None
    parent = None

    def eventFilter(self, source, event):
        if self.tableWidget.selectedIndexes() != []:

            if event.type() == QtCore.QEvent.MouseButtonPress:
                if event.button() == QtCore.Qt.LeftButton:
                    row = self.tableWidget.currentRow()
                    self.parent.load_row(row)

                elif event.button() == QtCore.Qt.RightButton:
                    row = self.tableWidget.currentRow()
                    self.parent.load_row(row)

        return QtCore.QObject.event(source, event)


def my_converter(my_data):
    def cvt(data):
        try:
            return ast.literal_eval(data)
        except Exception as e:
            return str(data)

    return tuple(map(cvt, my_data))


def show_dialog(message, msg_type=""):
    dialog = QDialog()
    dialog.setWindowTitle("Customer")

    q_btn = QDialogButtonBox.Ok | QDialogButtonBox.Cancel

    button_box = QDialogButtonBox(q_btn)
    button_box.accepted.connect(dialog.accept)
    button_box.rejected.connect(dialog.reject)

    message_lbl = QLabel(message)
    layout = QVBoxLayout()
    layout.addWidget(message_lbl)
    layout.addWidget(button_box)
    dialog.setLayout(layout)
    # dialog.setWindowIcon(msg_type)
    dialog.exec()


if __name__ == "__main__":
    gui_main = GUIMain()
    gui_main.setup_gui()
